Nettoyage de données et analyse basique en utilisant Pandas et nympy. source des données: cours introduction à  python

In [5]:
# Importation des libs

import pandas as pd
import numpy as np

#Importation de données
imdb=pd.read_csv("./......")
imdb.head(1)

,Titre,Date parution,Genre,Durée,Pays,Langue,Réalisateur,Auteur,Producteur,Acteurs,Note,Votes,Note hommes,Votes hommes,Note femmes,Votes femmes,Note USA,Votes USA,Note hors USA,Votes hors USA
0,Miss Jerry,1894-10-09,Romance,45.0,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",5.9,154.0,6.2,97.0,6.0,35.0,6.4,51.0,6.0,70.0

In [6]:
#renommer les colonnes ayant un espace dans le nom, remplacer l'espace par underscore.
imdb=imdb.rename(columns= {"Date parution":"Date_parution",
                         
                          "Note hommes":"Note_hommes",  
                          
                          "Votes hommes":"Votes_hommes", 
                         
                          "Note femmes":"Note_femmes",
                         
                          "Votes femmes":"Votes_femmes", 
                         
                          "Note USA":"Note_USA",	
                         
                         "Votes USA":"Votes_USA",
                         
                         "Note hors USA":"Note_hors_USA",
                         
                         "Votes hors USA":"Votes_hors_USA"
                         
                        }
                )

imdb.head(1)

,Titre,Date_parution,Genre,Durée,Pays,Langue,Réalisateur,Auteur,Producteur,Acteurs,Note,Votes,Note_hommes,Votes_hommes,Note_femmes,Votes_femmes,Note_USA,Votes_USA,Note_hors_USA,Votes_hors_USA
0,Miss Jerry,1894-10-09,Romance,45.0,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",5.9,154.0,6.2,97.0,6.0,35.0,6.4,51.0,6.0,70.0

In [7]:
imdb.shape

(84429, 20)

Quel est le pays d'origine du 405e film affiché dans la liste?
Par exemple, le pays d'origine du 1er film affiché dans la liste est USA.

In [9]:
pays_origine=imdb.loc[404,"Pays"]

print("le pays d'origine du 405e film affiché dans la liste est: {} ".format(pays_origine))

le pays d'origine du 405e film affiché dans la liste est: Germany

Quelle est la note médiane des films de genre biographique?

In [11]:
note_mediane=imdb[imdb["Genre"]=="Biography"]["Note"].median()

print("La note médiane des films de genre biographique est : {} ".format(note_mediane))

La note médiane des films de genre biographique est : 6.7

Combien y a-t-il de comédies ayant une durée entre 90 minutes et 120 minutes inclusivement?

In [13]:
#selectionner les films ayant une durée entre 90 minutes et 120 minutes inclusivement 

df_duree90to120 = imdb[(imdb["Durée"] >= 90) & (imdb["Durée"] <= 120)]


#calculer le nombre de genre comédie ayant une durée entre 90 minutes et 120 minutes inclusivement

nombre_comedie = df_duree90to120[df_duree90to120["Genre"]=="Comedy"]["Genre"].count()

print("Le nombre de comédies ayant une durée entre 90 minutes et 120 minutes inclusivement est: {} ".format(nombre_comedie))

Le nombre de comédies ayant une durée entre 90 minutes et 120 minutes inclusivement est: 14718

Combien y a-t-il de films pour lesquels l'auteur est manquant?

In [15]:
imdb["Auteur"].isnull().sum()

1528

In [87]:
imdb[imdb["Durée"] < 100]

,Titre,Date_parution,Genre,Durée,Pays,Langue,Réalisateur,Auteur,Producteur,Acteurs,Note,Votes,Note_hommes,Votes_hommes,Note_femmes,Votes_femmes,Note_USA,Votes_USA,Note_hors_USA,Votes_hors_USA
0,Miss Jerry,1894-10-09,Romance,45.0,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",5.9,154.0,6.2,97.0,6.0,35.0,6.4,51.0,6.0,70.0
1,The Story of the Kelly Gang,1906-12-26,Biography,70.0,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",6.1,589.0,6.1,425.0,6.2,50.0,6.0,96.0,6.2,331.0
2,Den sorte drøm,1911-08-19,Drama,53.0,Germany,NaN,Urban Gad,Urban Gad,Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",5.8,188.0,5.9,146.0,5.7,15.0,6.2,31.0,5.9,123.0
4,L'Inferno,1911-03-06,Adventure,68.0,Italy,Italian,Francesco Bertolini,Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",7.0,2237.0,7.0,1607.0,7.2,215.0,7.0,488.0,7.0,1166.0
5,Madame DuBarry,1919-11-26,Biography,85.0,Germany,German,Ernst Lubitsch,Norbert Falk,Projektions-AG Union (PAGU),"Pola Negri, Emil Jannings, Harry Liedtke, Edua...",6.8,753.0,6.6,530.0,7.4,93.0,6.6,139.0,6.8,455.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84421,La reina de los lagartos,2019-10-05,Fantasy,63.0,NaN,Spanish,Juan González,Juan González,Aquí y Allí Films,"Javier Botet, Bruna Cusí, Miki Esparbé, Ivan L...",4.8,103.0,4.6,55.0,5.3,13.0,2.3,10.0,5.2,49.0
84422,Enemy Lines,2020-05-04,War,92.0,UK,English,Anders Banke,Michael Wright,Happy Hour Films,"Ed Westwick, John Hannah, Tom Wisdom, Corey Jo...",5.0,764.0,4.1,310.0,5.5,36.0,4.5,61.0,4.1,203.0
84425,Le lion,2020-01-29,Comedy,95.0,France,French,Ludovic Colbeau-Justin,Alexandre Coquelle,Monkey Pack Films,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",5.3,398.0,5.3,267.0,6.0,26.0,6.3,22.0,5.3,214.0
84427,Sokagin Çocuklari,2019-03-15,Drama,98.0,Turkey,Turkish,Ahmet Faik Akinci,Ahmet Faik Akinci,Gizem Ajans,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",6.4,194.0,3.1,10.0,4.0,2.0,1.7,5.0,5.8,5.0
84428,La vida sense la Sara Amat,2020-02-05,Drama,74.0,Spain,Catalan,Laura Jou,Coral Cruz,La Xarxa de Comunicació Local,"Maria Morera Colomer, Biel Rossell Pelfort, Is...",6.7,102.0,6.6,68.0,6.9,15.0,6.7,13.0,6.7,60.0

Quelle est la langue du film le plus long?

In [17]:
# la durée la plus longue
imdb["Durée"].max()

#le film le plus long
imdb[imdb["Durée"]==imdb["Durée"].max()]["Titre"]

#la langue du film le plus long
langue_film_lepluslong = imdb[imdb["Durée"]==imdb["Durée"].max()]["Langue"]


print("La langue du film le plus long est: {} ".format(langue_film_lepluslong.values[0]))

La langue du film le plus long est: Catalan

Combien de jours faudrait-il pour réussir à écouter tous les films de cette liste de façon consécutive?

In [19]:
# la durée totale, en minutes, de tous les films de la liste.
duree_totale= imdb["Durée"].sum()

#diviser par 60 mins pour calculer la durée en en heures,ensuite par 24h pour avoir la durée en jours.
jours=(duree_totale/60)/24

#nombre de jours arrondi
np.round(jours)

5833.0

Dans quel genre trouve-t-on la plus haute proportion de films provenant du Canada?
Considérez uniquement les films pour lesquels le genre et le pays ne sont pas des valeurs manquantes.

In [21]:
#supprimer les lignes contenant des valeurs manquantes dans les colonnes Genre et Pays
df_sans_na_genre_pays=imdb.dropna(subset=["Genre","Pays"])

# condition  pour filtrer les films provenants du Canada 
condition1=[df_sans_na_genre_pays["Pays"]=="Canada"]

#calculer l'effectif par genre des films provenants du Canada et le reste du monde par un tabeau croisé dynamique, pour compter l'effectif du Canada si
#La condition est vérifée( True), et l'effectif du reste du monde si la condition n'est pas vérifiée( False)

effectif=df_sans_na_genre_pays.pivot_table(values = "Titre",columns=condition1, index = "Genre", aggfunc ="count")


#calculer les proportions par genre des films provenants du Canada(condition est True) par rapport au total par genre
proportions=effectif[True]/effectif.sum(axis=1)

#sélectionner le genre ayant la plus haute proportion de films provenant du Canada
proportion_max=proportions.idxmax()

print("Le genre ayant la plus haute proportion de films provenant du Canada est: {}".format(proportion_max))

Le genre ayant la plus haute proportion de films provenant du Canada est: Thriller


tab=pd.crosstab(df_sans_na_genre_pays["Genre"],df_sans_na_genre_pays["Pays"], margins=True)
tab[["Canada","All"]]
#prop=tab["Canada"]/tab["All"]
#prop.idxmax()

Quel pays entre la France et le Royaume-Uni (UK) a-t-il le plus petit nombre de films en langue italienne?
On s'intéresse au nombre absolu et non à la proportion.

In [24]:
#filtrer les films dont le pays est la France ou UK
film_uk_fr=imdb[(imdb["Pays"]=="France") | (imdb["Pays"]=="UK")]


#films dont le pays est la france ou UK et en langue italienne
uk_fr_italien= film_uk_fr[film_uk_fr["Langue"]=="Italian"]

# pays entre la France et UK qui a le plus petit nombre de films en langue italienne
nombre_min=uk_fr_italien["Pays"].value_counts().idxmin()

print("Le pays entre la France et le Royaume-Uni (UK) ayant le plus petit nombre de films en langue italienne est: {}".format(nombre_min))

Le pays entre la France et le Royaume-Uni (UK) ayant le plus petit nombre de films en langue italienne est: UK

Quels sont les 3 genres de films avec les durées moyennes les plus longues?

In [26]:
#calculer les durées moyenne par genre de films
duree_moyenne=imdb.pivot_table(values = "Durée", index = "Genre", aggfunc ="mean")

#trier les genres de film par ordre decroissant des durées moyennes
duree_moyenne_triee=duree_moyenne.sort_values("Durée", ascending = False)

#sélectionner les trois premières lignes qui représentent les 3 genres de films avec les durées moyennes les plus longues.
top3_durees=duree_moyenne_triee.iloc[0:3]
top3_durees

                Durée
Genre
Biography  114.206468
History    109.077922
Romance    107.892663

In [27]:

#afficher uniquement la liste des genres 
list(top3_durees.index)

['Biography', 'History', 'Romance']

Quelle proportion des films provient de l'un des 5 pays ayant produit le plus grand nombre de films?

In [29]:
#nombre de films par pays, triés par ordre décroissant
nombre_par_pays=imdb.pivot_table(values = "Titre", index = "Pays", aggfunc ="count").sort_values("Titre", ascending = False)

#calculer les proportions de films par pays
proportion_pays=nombre_par_pays/imdb["Titre"].count()

#proportions des films, des 5 pays ayant produit le plus grand nombre de films
top_5=proportion_pays.iloc[0:5]
top_5

           Titre
Pays
USA     0.362103
India   0.071480
UK      0.068993
France  0.060382
Italy   0.043765

In [30]:

#tirage aléatoire d'une proportion des films, parmi les 5 pays ayant produit le plus grand nombre de films
one_proportion = top_5.sample(n=1)
one_proportion.iloc[0,0]

0.06038209619917327

Quelle est la proportion des films qui sont des films d'aventure?
Considérez uniquement les films pour lesquels le genre est connu.

In [32]:
#supprimer les films ayant les valeurs manquantes dans la colonne genre.
films_genre_connue=imdb.dropna(subset=["Genre"])

# nombre de films par genre
nombre_par_genre=films_genre_connue["Genre"].value_counts()

#proportion des films qui sont des films d'aventure 
nombre_par_genre.loc["Adventure"]/films_genre_connue["Genre"].count()

0.04210627163095937

 En moyenne, combien de votes supplémentaires reçoivent les films qui sont longs en comparaison des les films qui ne le sont pas?
on considère qu'un film est long à partir d'une durée de 125 minutes. Considérez uniquement les films pour lesquels la durée est connue.

In [34]:

#créer un df, nommé df_durée_connue, en supprimant tous les films avec des durées inconnues.

df_durée_connue=imdb.dropna(subset=["Durée"]) #le parametre subset pour spécifier la colonne ou se trouve les vides

#filtrer les films longs
film_long = df_durée_connue[df_durée_connue["Durée"] >= 120]

#sélectionner les films courts
film_court = df_durée_connue[df_durée_connue["Durée"]<120]

#calculer la difference des votes moyens des filtm longs et les votes moyens des films courts 
différence_votes_moyen=film_long["Votes"].mean()-film_court["Votes"].mean()

# différence de votes moyens arrondie 
np.round(différence_votes_moyen)

18644.0

Quelle est la durée moyenne des films par décennie?
Une décennie commence à l'année 0 et se termine à l'année 9.

In [33]:



#Identifier l'année de sortie pour chaque film dans une colonne, ensuite grouper les films par décennie. Pour l'analyse,l'index est utilisé pour identifier l'année

#indexer le dataframe par des périodes de l'année de sortie pour chaque film(colonne "Date_parution"),
# par la méthode PeriodIndex et le paramètre de fréquence annuelle (freq="Y")

df_indexé=imdb.copy()

df_indexé.index = pd.PeriodIndex(df_indexé["Date_parution"], freq="Y")
df_indexé.index=df_indexé.index.rename("Période_parution")


#former des décennies identifiées par l'année de début de chaque décennie, et les grouper par la durée moyenne

durée_par_decennie=df_indexé.groupby((df_indexé.index.year//10)*10)["Durée"].mean()

print(durée_par_decennie)

Période_parution
1890     45.000000
1900     70.000000
1910     80.531250
1920     88.405751
1930     82.184639
1940     89.387222
1950     93.179063
1960     99.572965
1970    100.073488
1980    101.441568
1990    103.338102
2000    102.527912
2010    102.044482
2020    101.647328
Name: Durée, dtype: float64

In [37]:
df_indexé["Décennie"] = (((df_indexé.index.year + 1)// 10)) * 10
df_indexé

,Titre,Date_parution,Genre,Durée,Pays,Langue,Réalisateur,Auteur,Producteur,Acteurs,...,Votes,Note_hommes,Votes_hommes,Note_femmes,Votes_femmes,Note_USA,Votes_USA,Note_hors_USA,Votes_hors_USA,Décennie
Période_parution,,,,,,,,,,,,,,,,,,,,,
1894,Miss Jerry,1894-10-09,Romance,45.0,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",...,154.0,6.2,97.0,6.0,35.0,6.4,51.0,6.0,70.0,1890
1906,The Story of the Kelly Gang,1906-12-26,Biography,70.0,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",...,589.0,6.1,425.0,6.2,50.0,6.0,96.0,6.2,331.0,1900
1911,Den sorte drøm,1911-08-19,Drama,53.0,Germany,NaN,Urban Gad,Urban Gad,Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",...,188.0,5.9,146.0,5.7,15.0,6.2,31.0,5.9,123.0,1910
1912,Cleopatra,1912-11-13,Drama,100.0,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",...,446.0,5.1,299.0,5.9,39.0,5.5,207.0,4.7,105.0,1910
1911,L'Inferno,1911-03-06,Adventure,68.0,Italy,Italian,Francesco Bertolini,Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",...,2237.0,7.0,1607.0,7.2,215.0,7.0,488.0,7.0,1166.0,1910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,Manoharam,2019-09-27,Comedy,122.0,India,Malayalam,Anvar Sadik,NaN,chakkalakal Films,"Vineeth Sreenivasan, Aparna Das, Basil Joseph,...",...,491.0,6.7,289.0,7.3,8.0,7.0,35.0,6.5,168.0,2020
2020,Le lion,2020-01-29,Comedy,95.0,France,French,Ludovic Colbeau-Justin,Alexandre Coquelle,Monkey Pack Films,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",...,398.0,5.3,267.0,6.0,26.0,6.3,22.0,5.3,214.0,2020
2020,De Beentjes van Sint-Hildegard,2020-02-13,Comedy,103.0,Netherlands,German,Johan Nijenhuis,Radek Bajgar,Johan Nijenhuis & Co,"Herman Finkers, Johanna ter Steege, Leonie ter...",...,724.0,7.8,412.0,7.6,109.0,6.8,13.0,7.7,388.0,2020
2019,Sokagin Çocuklari,2019-03-15,Drama,98.0,Turkey,Turkish,Ahmet Faik Akinci,Ahmet Faik Akinci,Gizem Ajans,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",...,194.0,3.1,10.0,4.0,2.0,1.7,5.0,5.8,5.0,2020
2020,La vida sense la Sara Amat,2020-02-05,Drama,74.0,Spain,Catalan,Laura Jou,Coral Cruz,La Xarxa de Comunicació Local,"Maria Morera Colomer, Biel Rossell Pelfort, Is...",...,102.0,6.6,68.0,6.9,15.0,6.7,13.0,6.7,60.0,2020


Quel est l'acteur ayant participé au plus grand nombre de films américains entre les années 1990 et 1999 inclusivement?

In [38]:
#sélectionner les films  entre les années 1990 et 1999 inclusivement

films_90to99=df_indexé[(df_indexé.index.year >=1990) & (df_indexé.index.year<=1999)]

#films américains entre les années 1990 et 1999 inclusivement

film_USA= films_90to99[films_90to99["Pays"]=="USA"]

# séparer les noms d'acteurs séparés par des virgules, par la methode str.split(","), ensuite mettre chaque nom dans une ligne différente
#pour former une série contenant des noms d'acteurs, par la methode .explode()

serie_des_acteurs=film_USA["Acteurs"].str.split(",").explode()

# supprimer les vides dans les noms par str.strip(), pour compter correctement les mêmes noms d'acteur.

serie_des_acteurs = serie_des_acteurs.str.strip()


#déterminer le nom de l'acteur qui a le plus de participations
top_acteur = serie_des_acteurs.value_counts().idxmax()


print(top_acteur)

Samuel L. Jackson

Le public est-il plus exigeant à l'égard des films ne provenant pas de son marché? Pour répondre à la question, affichez la différence entre la note moyenne des films provenant du même marché que le public et la note moyenne des films ne provenant pas du même marché que le public.

Considérez deux marchés différents : le marché américain et le marché international. Un film est associé au marché américain s'il provient des États-Unis. Un film est associé au marché international s'il ne provient pas des États-Unis. Le public d'un film est associé au marché américain si au moins 25% des votes d'origine connue proviennent des États-Unis. Le public d'un film est international dans le cas contraire. Les films proviennent donc du même marché que le public lorsque les deux catégorisations sont à la fois américaines ou internationales.

Considérez uniquement les films ayant reçu au moins 500 votes, que leur origine soit connue ou non, pour l'analyse.

In [40]:


#1)selectioner les film ayant reçu au moins 500 votes

films_top_votes= imdb[imdb["Votes"] >= 500]



#2)identifier le marché de chaque film dans une nouvelle colonne nommée "Marché", par la fontion marché_film et la methode .apply()
"""
cette fonction retourne le type de marché( NaN,Americain ou Internationl), selon l'élément reçu de la série( ici appliquée à la colonne "Pays").
pour les films d'origine inconnue, le marché est considéré comme inconnu, valeur manquante(NaN).
"""


def marché_film (pays):

    if pd.isna(pays):
        marche = np.nan

    elif pays== "USA":
        marche="Americain"
    else:
        marche="International"
        
    return marche

films_top_votes2=films_top_votes.copy()

films_top_votes2["Marché"]=films_top_votes2["Pays"].apply(marché_film)






#3)identifier le public de chaque film dans une nouvelle colonne nommée "Public", par la fonction public_film et la méthode .apply(lambda row:)

#  Le public d'un film est associé au marché américain si au moins 25% des votes d'origine connue proviennent des USA

# Les votes d'origine connue inclus les votes USA et les votes hors USA(sans les votes des utilisateurs n'ayant pas complété leur origine)

"""
la fonction retourne le type de Public( Americain ou Internationl), selon la proportion 
des votes USA calculée pour chaque film, sur la base des deux l'éléments reçus  des deux 
series(ici appliquée aux colonnes "Votes_hors_USA" et "Votes_USA").
l'utilisation de lmbda row permets de passer les deux arguments de la fonction  pour chaque ligne.
"""

def public_film (vote,votes_USA):

    if (votes_USA/(votes_USA + vote)) >= 0.25:
        public="Americain"
    else:
        public="International"
        
    return public


films_top_votes2["Public"]=films_top_votes2.apply(lambda row:public_film(row["Votes_hors_USA"], row["Votes_USA"]), axis=1)
    
films_top_votes2.head(1)



#4) Calcul des notes moyennes

# 4.1)calculer la notes moyenne des film provenants de même charché que le public
moy1 = films_top_votes2[films_top_votes2["Marché"] == films_top_votes2["Public"]]["Note"].mean()

#4.2)calculer la notes moyennes des film ne provenant pas de même marché que le public

#retirer les notes des films ayant un marché inconnu
films_top_votes3 = films_top_votes2.dropna(subset=["Marché"])

#calculer  la note moyenne ou le marché est different du public
                                        
moy2 = films_top_votes3[films_top_votes3["Marché"] != films_top_votes3["Public"]]["Note"].mean()

#4.3)calculer la différence des deux moyennes
moy1-moy2

0.07767536954151755



La différence des deux moyennes observées dans cet échantillon est approximativement nulle, en tenant compte de l'échelle de notation qui est entre 0 et 10.

**Références externes:**

https://wesmckinney.com/book/python-builtin.html#functions

https://wesmckinney.com/book/time-series